# Generated by Django 6.0.4 on 2026-05-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawnApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Basic Lawn Mowing - $65", "Basic Lawn Mowing - $65"),
                            ("Fertilization - $40", "Fertilization - $40"),
                            (
                                "Full Service Package - $120",
                                "Full Service Package - $120",
                            ),
                            ("Bush Trimming - $35+", "Bush Trimming - $35+"),
                            ("Leaf Cleanup - $45+", "Leaf Cleanup - $45+"),
                            ("Sprinkler Check - $50+", "Sprinkler Check - $50+"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
