# Generated by Django 6.0.4 on 2026-05-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lawnApp", "0002_appointment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("date", "time")},
        ),
    ]
